@echo off
echo Starting MediaTracker in development mode...
echo.
echo Starting Angular development server...
start "Angular Dev Server" npm run start
echo.
echo Waiting for Angular to start...
timeout /t 10 /nobreak > nul
echo.
echo Starting Electron...
npm run electron
